### ISSUE TITLE
How to install the demo content?

### ISSUE THREAD

**Issue by lawxen** [centarro/commerce-kickstart-project#1]
After fresh install commerce-kickstart-project, no content.

**Comment by lawxen** [comment]
![image](https://user-images.githubusercontent.com/20714821/141653561-f57327e8-6e6d-44f3-be33-acd1b9afeb31.png)  

![image](https://user-images.githubusercontent.com/20714821/141653509-a9b23afc-7a06-46e9-b1ef-3529ee04cf91.png)

**Comment by lawxen** [comment]
[Commerce Demo didn't work with commerce kickstart](https://www.drupal.org/project/commerce_kickstart/issues/3249284)

**Comment by dwkitchen** [comment]
The Kickstart Template won't include demo content; that will be the demo project https://github.com/drupalcommerce/demo-project

Our intention is to prevent people from starting a site with the demo content installed, rather they should start with a clean install.
