### ISSUE TITLE
Error installing -> Cannot apply patch #3348151 - Fix console errors with D10

### ISSUE THREAD

**Issue by jhordybarrera** [centarro/commerce-kickstart-project#6]
Steps to reproduce
```
composer create-project -s dev centarro/commerce-kickstart-project kickstart
```
Capture
![Install Error](https://github.com/centarro/commerce-kickstart-project/assets/52984437/cafa250c-c5f0-441f-bc1b-f486630162a3)

**Comment by tarun0206** [comment]
The problem is that you are installing it on windows. Windows don't provide 'patch' natively so you have to install it manually and then add it to the path.

I will suggest you install it using git bash. If you want more help , let me know.

**Comment by jhordybarrera** [comment]
Working now correctly on windows, and linux!
![image](https://github.com/centarro/commerce-kickstart-project/assets/52984437/a1811ccd-496e-4d0c-bc34-1e3465b9c1d3)
