### ISSUE TITLE
demo not working with recent updates

### ISSUE THREAD

**Issue by Amunhateb** [centarro/commerce-kickstart-project#9]
Hello guys. I've recently (approx 1 week ago) tried run your demo and it was working fine. I've moved to another place with the same php ddev and docker configuration but now it's not working.

I can't complete initial setup. It fails with some dependency resolve issue.

![изображение](https://github.com/centarro/commerce-kickstart-project/assets/4275477/dd30c92d-8dcd-4117-bc4f-4470429ec88c)

I can confirm that it was working 1 week ago with simple 3 steps
```
composer create-project -s dev centarro/commerce-kickstart-project kickstart
cd kickstart
composer require drupal/commerce_demo:^3.0
```
@jsacksick @rszrama could you guys pls take a look? It reproduce itself 100% on two PCs already.

**Comment by rszrama** [comment]
I just ran a clean test and everything worked fine. Running Mac OS 14.2.1, Docker 4.26.1, ddev 1.22.6.

Somehow you're missing basic Drupal configuration, don't think we'll be able to help you figure out why.

**Comment by Amunhateb** [comment]
thats very strange.. I am doing 3 simple commands. I am on debian 12 with php 8.1. I am using latest Composer. What can go wrong.

**Comment by Amunhateb** [comment]
Okay, I've found out why I have the issue. ddev doesn't actually drop docker volumes and reuses them if names are the same. So be sure to drop volumes if you are recreating project with the same name.
`docker volume ls` and look at the result
